### ISSUE TITLE
Add new datastructures

### ISSUE THREAD

**Issue by clarkenciel** [proud-dogs/rollercoaster#10]
*** TODO update shape of loan datastructure:
    loan: {
      title: String,
      amountOwed: Number,
      interestRate: InterestRate,
      compoundingFrequency: Frequency
    }
*** TODO add InterestRate datastructure:
    InterestRate {
      rate: Number,
      type: Frequency
    }
*** TODO add Frequency Enum:
    FREQUENCY = {
      CONTINUOUSLY: 'Continuously',
      DAILY: 'Daily',
      MONTHLY: 'Monthly',
      YEARLY: 'Yearly',
    }

**Comment by fakemonster** [comment]
@clarkenciel hoo boy we made this tougher for ourselves. two issues arise from this:

1. the number of months to repay (monthsToPayOffLoan) and the monthly payment (monthlyPayment) together comprise what i'm tentatively calling a "payment plan", and we have to store that in state somewhere. three options off the top of my head:
> (A) As a property of the loan-form state itself, keep an array of paymentPlans (properties id, monthlyPayment and monthsToPayOffLoan), and when we create a new loan we simultaneously create a default paymentPlan with the same id. this is my least favorite because it seems like we're just making the code harder to use/understand with no foreseen benefit.
> (B) what we're calling a "loan" now becomes an object with three properties: id, debt (itself an object with all the above loan values excluding id), and paymentPlan (an object with monthsToPayOffLoan and monthlyPayment).
> (C) we keep things as-is but put monthlyPayment and monthsToPayOffLoan right back into the loan object where they were before. I think I prefer (B) but I'm open to suggestion here. Issue #2 may influence your own opinion.

2. Whenever the loan changes (other than title), we have to update the payment plan. One of the two variables in that plan should remain fixed (we could theoretically change both by the same percentage, but that seems extremely difficult and extremely unnecessary). Do we make variable locking an option for the user, or just pick one to lock ourselves? I'm honestly not sure. I'd like to defer that control to the user but it seems like the tool becomes confusing at that point. If we DO defer it, I think that control should be singular, controlling all loans with a single switch/checkbox/whatever. If we DON'T, we should lock down the monthly payment, purely because our original use case would do that.

Thoughts????????????????????????????????????????

**Comment by clarkenciel** [comment]
I like option B. fwiw option A is how you would implement it in a relational database to achieve the concept of option B so they aren't _so_ different from one another. B makes more sense conceptually though. The naming here is great, too.

Re: updating the payment plan, wouldn't we only be updating a single value at a time? We would have a `handleLoanUpdate` action that updates the part of the payment plan changed by the user and then recomputes the other values in the plan. I don't think it would be physically possible for a human to change both at once. Although that's something to think about if we move this logic to a server behind an API for some reason.

Re: locking, I think we should allow it, both globally and locally. A user should be allowed to check a box that says "lock months to pay of for all loans" that then checks the boxes of all loans, and then i should be able to individually uncheck each loan (this would, of course, uncheck the global checkbox). It would be similar to the way multiple selection in Gmail works I'd think. The app would still update the locked field, but now the field would be greyed out and uneditable by the user.

Let me know if I haven't answered something fully or misunderstood!

**Comment by fakemonster** [comment]
Re: updating, it's not about updating one or the other within the payment plan, it's "how do we update the payment plan when the _loan_ changes?" Like if you change the interest rate, your payment plan suddenly becomes inaccurate, so we have to update either the monthsToPayOffLoan or the monthlyPayment. But the locking solves that for us.

*** TODO add `debt` datastructure identical to `loan` above but without id
*** TODO add paymentPlan datastructure:
paymentPlan: {
monthlyPayment: Number,
monthsToPayOffLoan: Number
}
*** TODO update loan datastructure:
loan: {
id: Number,
debt: debt,
paymentPlan: paymentPlan
}
*** TODO tests for all these bad boys

**Comment by clarkenciel** [comment]
I see now. I suppose in the case of a loan with no locks, we could assume that the `monthlyPayment` field should stay the same and update the `monthsToPayOffLoan` field

**Comment by fakemonster** [comment]
We could also just start out with one locked and have a radio for what you lock, idk but that's all a separate issue. For now let's just assume the `monthlyPayment` field stays the same, since it's harder to remember what you put in that in general

**Comment by fakemonster** [comment]
k i got hella models now, nothing else will work when i add them tho. do i make a pr? or do i stabilize first

**Comment by clarkenciel** [comment]
get your branch stable first.

**Comment by fakemonster** [comment]
Resolved via #22
